insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Asian', 61, 253);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Black or African American', 11676, 47141);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'American Indian or Alaska Native', 28, 135);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'White', 13115, 76834);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Asian', 371, 892);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Native Hawaiian', 15, 43);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Black or African American', 755, 1476);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'American Indian or Alaska Native', 4510, 7579);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'White', 3611, 11370);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Asian', 411, 1549);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Native Hawaiian', 44, 127);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Black or African American', 7589, 24741);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'American Indian or Alaska Native', 6113, 41508);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'White', 34371, 156219);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Other', 35, 122);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Asian', 188, 1219);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Native Hawaiian', 19, 117);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Black or African American', 7695, 34779);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'American Indian or Alaska Native', 36, 244);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'White', 12472, 76846);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Other', 189, 1005);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'Asian', 6829, 20143);
