insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Asian', 61, 253);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Black or African American', 11676, 47141);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'American Indian or Alaska Native', 28, 135);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'White', 13115, 76834);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AL', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Asian', 371, 892);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Native Hawaiian', 15, 43);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Black or African American', 755, 1476);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'American Indian or Alaska Native', 4510, 7579);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'White', 3611, 11370);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AK', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Asian', 411, 1549);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Native Hawaiian', 44, 127);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Black or African American', 7589, 24741);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'American Indian or Alaska Native', 6113, 41508);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'White', 34371, 156219);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AZ', 'Other', 35, 122);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Asian', 188, 1219);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Native Hawaiian', 19, 117);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Black or African American', 7695, 34779);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'American Indian or Alaska Native', 36, 244);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'White', 12472, 76846);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('AR', 'Other', 189, 1005);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'Asian', 6829, 20143);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'Native Hawaiian', 1204, 3232);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'Black or African American', 54742, 122230);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'American Indian or Alaska Native', 1387, 4542);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'White', 191565, 689992);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CA', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'Asian', 316, 1770);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'Native Hawaiian', 41, 181);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'Black or African American', 5648, 22342);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'American Indian or Alaska Native', 400, 3064);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'White', 26262, 170258);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CO', 'Other', 59, 395);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'Asian', 146, 472);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'Native Hawaiian', 0, 2);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'Black or African American', 8236, 22450);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'American Indian or Alaska Native', 77, 214);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'White', 15696, 50121);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('CT', 'Other', 317, 1020);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'Asian', 36, 107);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'Native Hawaiian', 0, 1);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'Black or African American', 4893, 8814);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'American Indian or Alaska Native', 3, 13);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'White', 4094, 10873);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DE', 'Other', 27, 94);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'Asian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'Black or African American', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'American Indian or Alaska Native', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'White', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('FL', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'Asian', 322, 1417);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'Black or African American', 21866, 110486);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'American Indian or Alaska Native', 43, 327);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'White', 17568, 112406);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('GA', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'Asian', 916, 2382);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'Native Hawaiian', 1772, 5558);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'Black or African American', 348, 1158);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'American Indian or Alaska Native', 13, 37);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'White', 1313, 7102);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('HI', 'Other', 131, 4281);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'Asian', 77, 369);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'Native Hawaiian', 1, 4);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'Black or African American', 267, 1484);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'American Indian or Alaska Native', 284, 2122);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'White', 7216, 45964);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ID', 'Other', 463, 5729);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'Asian', 202, 264);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'Native Hawaiian', 0, 4);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'Black or African American', 22273, 38387);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'American Indian or Alaska Native', 5, 34);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'White', 5486, 20118);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IL', 'Other', 4, 29);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'Asian', 115, 663);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'Native Hawaiian', 6, 27);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'Black or African American', 9338, 33483);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'American Indian or Alaska Native', 27, 132);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'White', 14445, 81205);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IN', 'Other', 57, 473);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'Asian', 65, 442);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'Black or African American', 2530, 9719);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'American Indian or Alaska Native', 137, 981);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'White', 5976, 37184);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('IA', 'Other', 91, 511);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'Asian', 23, 334);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'Black or African American', 784, 6941);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'American Indian or Alaska Native', 26, 386);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'White', 3044, 32892);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KS', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'Asian', 61, 425);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'Native Hawaiian', 8, 144);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'Black or African American', 5637, 43989);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'American Indian or Alaska Native', 12, 148);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'White', 14326, 196583);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('KY', 'Other', 157, 1908);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'Asian', 210, 801);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'Black or African American', 27749, 84808);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'American Indian or Alaska Native', 85, 287);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'White', 16118, 67327);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('LA', 'Other', 20, 86);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'Asian', 41, 159);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'Native Hawaiian', 1, 9);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'Black or African American', 458, 1995);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'American Indian or Alaska Native', 78, 313);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'White', 6074, 31774);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ME', 'Other', 0, 53);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'Asian', 237, 1800);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'Native Hawaiian', 25, 202);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'Black or African American', 25514, 76397);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'American Indian or Alaska Native', 65, 231);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'White', 15692, 73586);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MD', 'Other', 0, 4);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'Asian', 557, 924);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'Native Hawaiian', 15, 47);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'Black or African American', 7804, 14036);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'American Indian or Alaska Native', 38, 110);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'White', 21733, 64755);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MA', 'Other', 686, 1583);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'Asian', 205, 729);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'Black or African American', 18732, 61598);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'American Indian or Alaska Native', 173, 1295);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'White', 26829, 120750);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MI', 'Other', 1183, 5520);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'Asian', 665, 2942);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'Native Hawaiian', 14, 62);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'Black or African American', 8427, 30499);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'American Indian or Alaska Native', 1419, 7059);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'White', 14226, 81602);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MN', 'Other', 181, 936);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'Asian', 28, 312);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'Native Hawaiian', 1, 17);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'Black or African American', 5238, 33022);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'American Indian or Alaska Native', 123, 1247);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'White', 2777, 26771);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MS', 'Other', 21, 104);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'Asian', 102, 619);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'Native Hawaiian', 54, 153);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'Black or African American', 13339, 50681);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'American Indian or Alaska Native', 34, 118);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'White', 23163, 119289);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MO', 'Other', 28, 105);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'Asian', 58, 162);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'Black or African American', 211, 519);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'American Indian or Alaska Native', 1416, 5064);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'White', 4590, 16598);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('MT', 'Other', 104, 367);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'Asian', 114, 429);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'Native Hawaiian', 0, 5);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'Black or African American', 3523, 10263);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'American Indian or Alaska Native', 443, 1796);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'White', 8317, 41563);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NE', 'Other', 57, 333);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'Asian', 987, 2951);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'Native Hawaiian', 30, 96);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'Black or African American', 10209, 31854);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'American Indian or Alaska Native', 288, 1630);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'White', 19244, 77103);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NV', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'Asian', 44, 276);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'Native Hawaiian', 0, 16);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'Black or African American', 541, 1957);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'American Indian or Alaska Native', 17, 41);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'White', 6592, 36767);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NH', 'Other', 60, 486);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'Asian', 592, 3070);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'Native Hawaiian', 9, 75);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'Black or African American', 14146, 95773);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'American Indian or Alaska Native', 81, 434);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'White', 19067, 135776);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NJ', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'Asian', 52, 145);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'Native Hawaiian', 14, 36);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'Black or African American', 1014, 3141);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'American Indian or Alaska Native', 2453, 11628);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'White', 10378, 46805);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NM', 'Other', 831, 1970);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'Asian', 374, 2083);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'Native Hawaiian', 2, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'Black or African American', 17557, 60407);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'American Indian or Alaska Native', 244, 1196);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'White', 28167, 138093);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NY', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'Asian', 256, 1536);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'Black or African American', 29956, 100238);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'American Indian or Alaska Native', 365, 1867);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'White', 29746, 131424);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('NC', 'Other', 2, 2);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'Asian', 34, 208);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'Black or African American', 635, 3019);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'American Indian or Alaska Native', 711, 4714);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'White', 2703, 20660);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('ND', 'Other', 74, 629);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'Asian', 148, 616);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'Native Hawaiian', 6, 22);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'Black or African American', 17429, 49794);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'American Indian or Alaska Native', 40, 129);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'White', 23325, 112987);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OH', 'Other', 10468, 25432);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'Asian', 91, 641);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'Native Hawaiian', 18, 99);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'Black or African American', 4392, 17724);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'American Indian or Alaska Native', 1499, 8649);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'White', 10912, 63386);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OK', 'Other', 104, 645);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'Asian', 274, 1434);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'Native Hawaiian', 107, 410);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'Black or African American', 1978, 9410);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'American Indian or Alaska Native', 346, 1741);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'White', 17877, 101962);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('OR', 'Other', 483, 2629);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'Asian', 428, 2411);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'Black or African American', 24824, 80577);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'American Indian or Alaska Native', 60, 262);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'White', 46380, 195331);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('PA', 'Other', 5, 12);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'Asian', 51, 197);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'Native Hawaiian', 0, 1);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'Black or African American', 1585, 4609);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'American Indian or Alaska Native', 15, 36);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'White', 4192, 15306);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('RI', 'Other', 34, 65);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'Asian', 74, 493);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'Native Hawaiian', 10, 50);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'Black or African American', 15139, 57204);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'American Indian or Alaska Native', 66, 307);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'White', 14785, 79913);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SC', 'Other', 62, 708);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'Asian', 46, 297);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'Native Hawaiian', 8, 68);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'Black or African American', 547, 2583);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'American Indian or Alaska Native', 2155, 12617);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'White', 3022, 18789);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('SD', 'Other', 318, 4010);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'Asian', 209, 1009);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'Native Hawaiian', 31, 150);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'Black or African American', 21946, 82773);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'American Indian or Alaska Native', 87, 386);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'White', 34568, 213912);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TN', 'Other', 117, 898);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'Asian', 1344, 6173);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'Native Hawaiian', 1102, 3018);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'Black or African American', 44287, 158833);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'American Indian or Alaska Native', 214, 976);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'White', 106311, 473130);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('TX', 'Other', 215, 1018);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'Asian', 539, 2433);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'Native Hawaiian', 5, 49);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'Black or African American', 875, 5313);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'American Indian or Alaska Native', 434, 3123);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'White', 10220, 78858);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('UT', 'Other', 952, 6723);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'Asian', 26, 114);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'Native Hawaiian', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'Black or African American', 228, 824);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'American Indian or Alaska Native', 0, 8);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'White', 2345, 10881);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VT', 'Other', 14, 68);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'Asian', 460, 2445);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'Native Hawaiian', 0, 1);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'Black or African American', 20362, 97292);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'American Indian or Alaska Native', 33, 164);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'White', 22748, 135980);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('VA', 'Other', 122, 1361);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'Asian', 1597, 4714);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'Native Hawaiian', 114, 216);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'Black or African American', 6934, 17428);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'American Indian or Alaska Native', 1149, 4973);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'White', 30713, 107784);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WA', 'Other', 1257, 3817);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'Asian', 16, 46);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'Native Hawaiian', 1, 5);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'Black or African American', 699, 3376);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'American Indian or Alaska Native', 6, 12);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'White', 4768, 23547);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WV', 'Other', 199, 1559);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'Asian', 349, 3049);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'Native Hawaiian', 22, 109);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'Black or African American', 10774, 45200);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'American Indian or Alaska Native', 979, 8114);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'White', 17290, 159739);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WI', 'Other', 264, 2142);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'Asian', 8, 73);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'Native Hawaiian', 2, 20);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'Black or African American', 145, 1023);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'American Indian or Alaska Native', 423, 3812);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'White', 2419, 20629);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('WY', 'Other', 0, 0);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'Asian', 2, 72);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'Native Hawaiian', 0, 8);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'Black or African American', 580, 11943);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'American Indian or Alaska Native', 0, 8);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'White', 44, 991);
insert into fbi_data (state_abv, race, violent_arrests, non_violent_arrests) values ('DC', 'Other', 4, 33);
