insert into prison_data (state_name, race, year, pop_count) values ('Federal', 'NULL', 2018, 179898);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '1', 2018, 50946);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '2', 2018, 66714);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '7', 2018, 56056);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '3', 2018, 2416);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '5', 2018, 3765);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Federal', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', 'NULL', 2018, 26841);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '1', 2018, 12566);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '2', 2018, 14080);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '7', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '3', 2018, 2);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '5', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '6', 2018, 192);
insert into prison_data (state_name, race, year, pop_count) values ('Alabama', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', 'NULL', 2018, 4380);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '1', 2018, 1877);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '2', 2018, 447);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '7', 2018, 125);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '3', 2018, 139);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '4', 2018, 85);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '5', 2018, 1679);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '6', 2018, 28);
insert into prison_data (state_name, race, year, pop_count) values ('Alaska', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', 'NULL', 2018, 42005);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '1', 2018, 16379);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '2', 2018, 6119);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '7', 2018, 16274);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '3', 2018, 210);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '5', 2018, 2249);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '6', 2018, 679);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '6', 2018, 27);
insert into prison_data (state_name, race, year, pop_count) values ('Arizona', '0', 2018, 68);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', 'NULL', 2018, 17799);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '1', 2018, 9802);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '2', 2018, 7277);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '7', 2018, 569);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '3', 2018, 69);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '4', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '5', 2018, 53);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '6', 2018, 17);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '6', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('Arkansas', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('California', 'NULL', 2018, 128625);
insert into prison_data (state_name, race, year, pop_count) values ('California', '1', 2018, 26921);
insert into prison_data (state_name, race, year, pop_count) values ('California', '2', 2018, 36491);
insert into prison_data (state_name, race, year, pop_count) values ('California', '7', 2018, 56731);
insert into prison_data (state_name, race, year, pop_count) values ('California', '3', 2018, 1423);
insert into prison_data (state_name, race, year, pop_count) values ('California', '4', 2018, 381);
insert into prison_data (state_name, race, year, pop_count) values ('California', '5', 2018, 1463);
insert into prison_data (state_name, race, year, pop_count) values ('California', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('California', '6', 2018, 5215);
insert into prison_data (state_name, race, year, pop_count) values ('California', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('California', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', 'NULL', 2018, 20372);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '1', 2018, 9339);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '2', 2018, 3517);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '7', 2018, 6411);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '3', 2018, 255);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '5', 2018, 729);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '6', 2018, 3);
insert into prison_data (state_name, race, year, pop_count) values ('Colorado', '0', 2018, 118);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', 'NULL', 2018, 13681);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '1', 2018, 4153);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '2', 2018, 5770);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '7', 2018, 3649);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '3', 2018, 65);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '5', 2018, 42);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '6', 2018, 2);
insert into prison_data (state_name, race, year, pop_count) values ('Connecticut', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', 'NULL', 2018, 6067);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '1', 2018, 2144);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '2', 2018, 3618);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '7', 2018, 293);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '3', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '5', 2018, 2);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '6', 2018, 4);
insert into prison_data (state_name, race, year, pop_count) values ('Delaware', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', 'NULL', 2018, 97538);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '1', 2018, 39167);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '2', 2018, 45735);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '7', 2018, 12239);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '3', 2018, 20);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '4', 2018, 10);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '5', 2018, 87);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '6', 2018, 275);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '6', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('Florida', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', 'NULL', 2018, 53647);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '1', 2018, 19123);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '2', 2018, 32133);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '7', 2018, 2120);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '3', 2018, 184);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '4', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '5', 2018, 21);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '6', 2018, 52);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '6', 2018, 13);
insert into prison_data (state_name, race, year, pop_count) values ('Georgia', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', 'NULL', 2018, 5375);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '1', 2018, 1294);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '2', 2018, 240);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '7', 2018, 247);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '3', 2018, 979);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '4', 2018, 2365);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '5', 2018, 22);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', 'NULL', 2018, 197);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '6', 2018, 31);
insert into prison_data (state_name, race, year, pop_count) values ('Hawaii', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', 'NULL', 2018, 8664);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '1', 2018, 6318);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '2', 2018, 237);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '7', 2018, 1326);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '3', 2018, 48);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '4', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '5', 2018, 310);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '6', 2018, 424);
insert into prison_data (state_name, race, year, pop_count) values ('Idaho', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', 'NULL', 2018, 39965);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '1', 2018, 12367);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '2', 2018, 22085);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '7', 2018, 5147);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '3', 2018, 145);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '5', 2018, 66);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', 'NULL', 2018, 62);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '6', 2018, 43);
insert into prison_data (state_name, race, year, pop_count) values ('Illinois', '0', 2018, 50);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', 'NULL', 2018, 26877);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '1', 2018, 16670);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '2', 2018, 8850);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '7', 2018, 1075);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '3', 2018, 66);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '4', 2018, 11);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '5', 2018, 50);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', 'NULL', 2018, 98);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '6', 2018, 57);
insert into prison_data (state_name, race, year, pop_count) values ('Indiana', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', 'NULL', 2018, 9419);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '1', 2018, 6164);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '2', 2018, 2398);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '7', 2018, 601);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '3', 2018, 82);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '5', 2018, 174);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Iowa', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', 'NULL', 2018, 10218);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '1', 2018, 5851);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '2', 2018, 2773);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '7', 2018, 1266);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '3', 2018, 97);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '5', 2018, 230);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '6', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kansas', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', 'NULL', 2018, 23431);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '1', 2018, 17844);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '2', 2018, 4929);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '7', 2018, 320);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '3', 2018, 37);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '5', 2018, 16);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', 'NULL', 2018, 266);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '6', 2018, 15);
insert into prison_data (state_name, race, year, pop_count) values ('Kentucky', '0', 2018, 4);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', 'NULL', 2018, 32397);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '1', 2018, 10547);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '2', 2018, 21700);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '7', 2018, 34);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '3', 2018, 38);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '4', 2018, 53);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '5', 2018, 24);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '6', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Louisiana', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', 'NULL', 2018, 2425);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '1', 2018, 1911);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '2', 2018, 234);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '7', 2018, 126);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '3', 2018, 14);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '4', 2018, 2);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '5', 2018, 71);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', 'NULL', 2018, 27);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '6', 2018, 40);
insert into prison_data (state_name, race, year, pop_count) values ('Maine', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', 'NULL', 2018, 18856);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '1', 2018, 4587);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '2', 2018, 13215);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '7', 2018, 700);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '3', 2018, 48);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '4', 2018, 15);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '5', 2018, 98);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '6', 2018, 165);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '6', 2018, 28);
insert into prison_data (state_name, race, year, pop_count) values ('Maryland', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', 'NULL', 2018, 8692);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '1', 2018, 3766);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '2', 2018, 2377);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '7', 2018, 2291);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '3', 2018, 120);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '5', 2018, 46);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '6', 2018, 92);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Massachusetts', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', 'NULL', 2018, 38761);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '1', 2018, 17061);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '2', 2018, 20718);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '7', 2018, 373);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '3', 2018, 101);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '4', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '5', 2018, 360);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '6', 2018, 143);
insert into prison_data (state_name, race, year, pop_count) values ('Michigan', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', 'NULL', 2018, 10101);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '1', 2018, 4654);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '2', 2018, 3620);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '7', 2018, 601);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '3', 2018, 277);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '5', 2018, 944);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '6', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('Minnesota', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', 'NULL', 2018, 19275);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '1', 2018, 7012);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '2', 2018, 12008);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '7', 2018, 177);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '3', 2018, 37);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '5', 2018, 30);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '6', 2018, 11);
insert into prison_data (state_name, race, year, pop_count) values ('Mississippi', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', 'NULL', 2018, 30369);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '1', 2018, 19442);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '2', 2018, 10125);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '7', 2018, 551);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '3', 2018, 72);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '5', 2018, 110);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '6', 2018, 69);
insert into prison_data (state_name, race, year, pop_count) values ('Missouri', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', 'NULL', 2018, 3765);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '1', 2018, 2772);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '2', 2018, 97);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '7', 2018, 74);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '3', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '5', 2018, 805);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '6', 2018, 17);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Montana', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', 'NULL', 2018, 5491);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '1', 2018, 2877);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '2', 2018, 1523);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '7', 2018, 767);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '3', 2018, 44);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '4', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '5', 2018, 225);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '6', 2018, 45);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '6', 2018, 4);
insert into prison_data (state_name, race, year, pop_count) values ('Nebraska', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', 'NULL', 2018, 13641);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '1', 2018, 5873);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '2', 2018, 4234);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '7', 2018, 2845);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '3', 2018, 402);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '5', 2018, 235);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '6', 2018, 52);
insert into prison_data (state_name, race, year, pop_count) values ('Nevada', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', 'NULL', 2018, 2745);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '1', 2018, 2300);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '2', 2018, 179);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '7', 2018, 173);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '3', 2018, 11);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '5', 2018, 11);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '6', 2018, 33);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '6', 2018, 38);
insert into prison_data (state_name, race, year, pop_count) values ('New Hampshire', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', 'NULL', 2018, 19362);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '1', 2018, 4125);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '2', 2018, 11847);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '7', 2018, 3031);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '3', 2018, 124);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '5', 2018, 13);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '6', 2018, 222);
insert into prison_data (state_name, race, year, pop_count) values ('New Jersey', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', 'NULL', 2018, 7030);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '1', 2018, 1786);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '2', 2018, 496);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '7', 2018, 4193);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '3', 2018, 17);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '4', 2018, 21);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '5', 2018, 474);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '6', 2018, 43);
insert into prison_data (state_name, race, year, pop_count) values ('New Mexico', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New York', 'NULL', 2018, 46636);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '1', 2018, 11248);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '2', 2018, 22513);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '7', 2018, 11322);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '3', 2018, 282);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '5', 2018, 394);
insert into prison_data (state_name, race, year, pop_count) values ('New York', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '6', 2018, 613);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '6', 2018, 264);
insert into prison_data (state_name, race, year, pop_count) values ('New York', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', 'NULL', 2018, 34899);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '1', 2018, 13801);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '2', 2018, 18009);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '7', 2018, 1894);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '3', 2018, 110);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '4', 2018, 21);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '5', 2018, 929);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '6', 2018, 135);
insert into prison_data (state_name, race, year, pop_count) values ('North Carolina', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', 'NULL', 2018, 1695);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '1', 2018, 1054);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '2', 2018, 188);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '7', 2018, 104);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '3', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '4', 2018, 3);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '5', 2018, 336);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', 'NULL', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('North Dakota', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', 'NULL', 2018, 50431);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '1', 2018, 25887);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '2', 2018, 22662);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '7', 2018, 1420);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '3', 2018, 66);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '5', 2018, 86);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '6', 2018, 310);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Ohio', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', 'NULL', 2018, 27709);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '1', 2018, 14537);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '2', 2018, 6981);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '7', 2018, 2064);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '3', 2018, 97);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '4', 2018, 27);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '5', 2018, 3175);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '6', 2018, 75);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Oklahoma', '0', 2018, 753);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', 'NULL', 2018, 15268);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '1', 2018, 11329);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '2', 2018, 1393);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '7', 2018, 1871);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '3', 2018, 228);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '4', 2018, 7);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '5', 2018, 434);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '6', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('Oregon', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', 'NULL', 2018, 47239);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '1', 2018, 20389);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '2', 2018, 21882);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '7', 2018, 4574);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '3', 2018, 127);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '5', 2018, 42);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '6', 2018, 225);
insert into prison_data (state_name, race, year, pop_count) values ('Pennsylvania', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', 'NULL', 2018, 2767);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '1', 2018, 1195);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '2', 2018, 803);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '7', 2018, 663);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '3', 2018, 43);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '5', 2018, 25);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '6', 2018, 38);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Rhode Island', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', 'NULL', 2018, 19033);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '1', 2018, 7057);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '2', 2018, 11335);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '7', 2018, 455);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '3', 2018, 20);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '4', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '5', 2018, 33);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '6', 2018, 132);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Carolina', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', 'NULL', 2018, 3948);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '1', 2018, 2128);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '2', 2018, 305);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '7', 2018, 146);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '3', 2018, 16);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '4', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '5', 2018, 1345);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '6', 2018, 7);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('South Dakota', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', 'NULL', 2018, 26321);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '1', 2018, 14514);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '2', 2018, 11125);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '7', 2018, 559);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '3', 2018, 84);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '5', 2018, 39);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Tennessee', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', 'NULL', 2018, 163628);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '1', 2018, 54983);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '2', 2018, 53424);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '7', 2018, 54325);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '3', 2018, 573);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '5', 2018, 94);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '6', 2018, 229);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Texas', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', 'NULL', 2018, 6648);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '1', 2018, 4217);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '2', 2018, 448);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '7', 2018, 1327);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '3', 2018, 74);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '4', 2018, 135);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '5', 2018, 330);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '6', 2018, 117);
insert into prison_data (state_name, race, year, pop_count) values ('Utah', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', 'NULL', 2018, 1659);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '1', 2018, 1418);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '2', 2018, 174);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '7', 2018, 4);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '3', 2018, 7);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '5', 2018, 15);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '6', 2018, 41);
insert into prison_data (state_name, race, year, pop_count) values ('Vermont', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', 'NULL', 2018, 36660);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '1', 2018, 15121);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '2', 2018, 20326);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '7', 2018, 1006);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '3', 2018, 159);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '5', 2018, 27);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '6', 2018, 21);
insert into prison_data (state_name, race, year, pop_count) values ('Virginia', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', 'NULL', 2018, 19523);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '1', 2018, 11547);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '2', 2018, 3440);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '7', 2018, 2542);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '3', 2018, 771);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '5', 2018, 998);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '6', 2018, 87);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '6', 2018, 138);
insert into prison_data (state_name, race, year, pop_count) values ('Washington', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', 'NULL', 2018, 6775);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '1', 2018, 5827);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '2', 2018, 861);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '7', 2018, 26);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '3', 2018, 5);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '4', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '5', 2018, 6);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '6', 2018, 49);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('West Virginia', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', 'NULL', 2018, 24064);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '1', 2018, 10899);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '2', 2018, 10065);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '7', 2018, 1887);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '3', 2018, 271);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '4', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '5', 2018, 928);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '6', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '6', 2018, 14);
insert into prison_data (state_name, race, year, pop_count) values ('Wisconsin', '0', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', 'NULL', 2018, 2543);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '1', 2018, 1917);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '2', 2018, 127);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '7', 2018, 327);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '3', 2018, 11);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '4', 2018, 9);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '5', 2018, 148);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', 'NULL', 2018, 0);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '6', 2018, 3);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '6', 2018, 1);
insert into prison_data (state_name, race, year, pop_count) values ('Wyoming', '0', 2018, 0);
