CREATE OR REPLACE FUNCTION refresh_views() RETURNS TRIGGER LANGUAGE plpgsql AS
$$ BEGIN
REFRESH MATERIALIZED VIEW fbi_data_states;
REFRESH MATERIALIZED VIEW arrest_rates;
REFRESH MATERIALIZED VIEW prison_data_states;
REFRESH MATERIALIZED VIEW currently_incarcerated_rate_white;
REFRESH MATERIALIZED VIEW currently_incarcerated_rate_black;
REFRESH MATERIALIZED VIEW cir;
REFRESH MATERIALIZED VIEW iat_view;
REFRESH MATERIALIZED VIEW state_ranks_adj;
REFRESH MATERIALIZED VIEW return_data;
RETURN NULL;
END $$;

CREATE TRIGGER footer_links_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON footer_links FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER states_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON states FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER state_ranks_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON state_ranks FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER races_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON races FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER iat_data_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON iat_data FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER prison_data_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON prison_data FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER fbi_data_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON fbi_data FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();
CREATE TRIGGER census_data_refresh_views AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON census_data FOR EACH STATEMENT EXECUTE PROCEDURE refresh_views();

REFRESH MATERIALIZED VIEW fbi_data_states;
REFRESH MATERIALIZED VIEW arrest_rates;
REFRESH MATERIALIZED VIEW prison_data_states;
REFRESH MATERIALIZED VIEW currently_incarcerated_rate_white;
REFRESH MATERIALIZED VIEW currently_incarcerated_rate_black;
REFRESH MATERIALIZED VIEW cir;
REFRESH MATERIALIZED VIEW iat_view;
REFRESH MATERIALIZED VIEW state_ranks_adj;
REFRESH MATERIALIZED VIEW return_data;