insert into census_data (state, race, year, population) values ('Alaska', 'Native Hawaiian or Pacific Islander', 2019, 10498);
insert into census_data (state, race, year, population) values ('California', 'Asian', 2019, 6110945);
insert into census_data (state, race, year, population) values ('Kentucky', 'Asian', 2019, 71504);
insert into census_data (state, race, year, population) values ('Alabama', 'Black or African American', 2019, 1313291);
insert into census_data (state, race, year, population) values ('Alaska', 'Black or African American', 2019, 27108);
insert into census_data (state, race, year, population) values ('Alabama', 'Other', 2019, 86874);
insert into census_data (state, race, year, population) values ('Alabama', 'American Indian or Alaska Native', 2019, 34799);
insert into census_data (state, race, year, population) values ('Hawaii', 'American Indian or Alaska Native', 2019, 5570);
insert into census_data (state, race, year, population) values ('Alabama', 'All races', 2019, 4903185);
insert into census_data (state, race, year, population) values ('Arkansas', 'Native Hawaiian or Pacific Islander', 2019, 11786);
insert into census_data (state, race, year, population) values ('Alaska', 'Asian', 2019, 47799);
insert into census_data (state, race, year, population) values ('Alaska', 'White or Caucasian', 2019, 477488);
insert into census_data (state, race, year, population) values ('Idaho', 'All races', 2019, 1787065);
insert into census_data (state, race, year, population) values ('Idaho', 'Black or African American', 2019, 16346);
insert into census_data (state, race, year, population) values ('Indiana', 'White or Caucasian', 2019, 5709592);
insert into census_data (state, race, year, population) values ('New York', 'Other', 2019, 515681);
insert into census_data (state, race, year, population) values ('California', 'Black or African American', 2019, 2552757);
insert into census_data (state, race, year, population) values ('Illinois', 'Asian', 2019, 747690);
insert into census_data (state, race, year, population) values ('Arkansas', 'Asian', 2019, 50403);
insert into census_data (state, race, year, population) values ('Idaho', 'Native Hawaiian or Pacific Islander', 2019, 3944);
insert into census_data (state, race, year, population) values ('Hawaii', 'Black or African American', 2019, 30958);
insert into census_data (state, race, year, population) values ('Idaho', 'White or Caucasian', 2019, 1662365);
insert into census_data (state, race, year, population) values ('Arkansas', 'American Indian or Alaska Native', 2019, 30717);
insert into census_data (state, race, year, population) values ('Arizona', 'All races', 2019, 7278717);
insert into census_data (state, race, year, population) values ('Alaska', 'All races', 2019, 731545);
insert into census_data (state, race, year, population) values ('Alaska', 'Other', 2019, 54699);
insert into census_data (state, race, year, population) values ('Arizona', 'American Indian or Alaska Native', 2019, 385903);
insert into census_data (state, race, year, population) values ('Iowa', 'All races', 2019, 3155070);
insert into census_data (state, race, year, population) values ('Illinois', 'All races', 2019, 12671821);
insert into census_data (state, race, year, population) values ('Hawaii', 'Other', 2019, 342288);
insert into census_data (state, race, year, population) values ('Washington', 'American Indian or Alaska Native', 2019, 146799);
insert into census_data (state, race, year, population) values ('Arizona', 'White or Caucasian', 2019, 6013442);
insert into census_data (state, race, year, population) values ('Florida', 'All races', 2019, 21477737);
insert into census_data (state, race, year, population) values ('Indiana', 'All races', 2019, 6732219);
insert into census_data (state, race, year, population) values ('Virginia', 'American Indian or Alaska Native', 2019, 46602);
insert into census_data (state, race, year, population) values ('West Virginia', 'Other', 2019, 32597);
insert into census_data (state, race, year, population) values ('Tennessee', 'Asian', 2019, 134076);
insert into census_data (state, race, year, population) values ('West Virginia', 'All races', 2019, 1792147);
insert into census_data (state, race, year, population) values ('Wisconsin', 'White or Caucasian', 2019, 5067781);
insert into census_data (state, race, year, population) values ('Washington DC', 'Asian', 2019, 31502);
insert into census_data (state, race, year, population) values ('Vermont', 'Asian', 2019, 11964);
insert into census_data (state, race, year, population) values ('Washington', 'Asian', 2019, 727986);
insert into census_data (state, race, year, population) values ('Tennessee', 'American Indian or Alaska Native', 2019, 32661);
insert into census_data (state, race, year, population) values ('Rhode Island', 'White or Caucasian', 2019, 885518);
insert into census_data (state, race, year, population) values ('Colorado', 'White or Caucasian', 2019, 5006612);
insert into census_data (state, race, year, population) values ('Washington DC', 'Other', 2019, 20129);
insert into census_data (state, race, year, population) values ('West Virginia', 'Asian', 2019, 14703);
insert into census_data (state, race, year, population) values ('Washington DC', 'All races', 2019, 705749);
insert into census_data (state, race, year, population) values ('North Carolina', 'Black or African American', 2019, 2330563);
insert into census_data (state, race, year, population) values ('Connecticut', 'All races', 2019, 3565287);
insert into census_data (state, race, year, population) values ('Oklahoma', 'White or Caucasian', 2019, 2927354);
insert into census_data (state, race, year, population) values ('Wyoming', 'Asian', 2019, 6571);
insert into census_data (state, race, year, population) values ('Wisconsin', 'Native Hawaiian or Pacific Islander', 2019, 3419);
insert into census_data (state, race, year, population) values ('Virginia', 'Asian', 2019, 589710);
insert into census_data (state, race, year, population) values ('Wyoming', 'Other', 2019, 12976);
insert into census_data (state, race, year, population) values ('Wisconsin', 'Other', 2019, 116784);
insert into census_data (state, race, year, population) values ('Alabama', 'Native Hawaiian or Pacific Islander', 2019, 5110);
insert into census_data (state, race, year, population) values ('Washington DC', 'Black or African American', 2019, 324484);
insert into census_data (state, race, year, population) values ('Tennessee', 'All races', 2019, 6829174);
insert into census_data (state, race, year, population) values ('Tennessee', 'Other', 2019, 136993);
insert into census_data (state, race, year, population) values ('Hawaii', 'Asian', 2019, 532190);
insert into census_data (state, race, year, population) values ('Vermont', 'All races', 2019, 623989);
insert into census_data (state, race, year, population) values ('Texas', 'Other', 2019, 601946);
insert into census_data (state, race, year, population) values ('Wisconsin', 'All races', 2019, 5822434);
insert into census_data (state, race, year, population) values ('Colorado', 'American Indian or Alaska Native', 2019, 92982);
insert into census_data (state, race, year, population) values ('South Carolina', 'White or Caucasian', 2019, 3532048);
insert into census_data (state, race, year, population) values ('Idaho', 'Asian', 2019, 27711);
insert into census_data (state, race, year, population) values ('Vermont', 'White or Caucasian', 2019, 588102);
insert into census_data (state, race, year, population) values ('California', 'White or Caucasian', 2019, 28424739);
insert into census_data (state, race, year, population) values ('Georgia', 'Black or African American', 2019, 3458147);
insert into census_data (state, race, year, population) values ('Kansas', 'White or Caucasian', 2019, 2513846);
insert into census_data (state, race, year, population) values ('Kansas', 'Other', 2019, 89131);
insert into census_data (state, race, year, population) values ('Kentucky', 'American Indian or Alaska Native', 2019, 13404);
insert into census_data (state, race, year, population) values ('Kansas', 'All races', 2019, 2913314);
insert into census_data (state, race, year, population) values ('Indiana', 'Native Hawaiian or Pacific Islander', 2019, 4539);
insert into census_data (state, race, year, population) values ('Georgia', 'Other', 2019, 235386);
insert into census_data (state, race, year, population) values ('Iowa', 'Black or African American', 2019, 128105);
insert into census_data (state, race, year, population) values ('Massachusetts', 'All races', 2019, 6892503);
insert into census_data (state, race, year, population) values ('Indiana', 'Other', 2019, 145402);
insert into census_data (state, race, year, population) values ('Maine', 'American Indian or Alaska Native', 2019, 9767);
insert into census_data (state, race, year, population) values ('Mississippi', 'American Indian or Alaska Native', 2019, 18705);
insert into census_data (state, race, year, population) values ('Minnesota', 'All races', 2019, 5639632);
insert into census_data (state, race, year, population) values ('Missouri', 'White or Caucasian', 2019, 5086188);
insert into census_data (state, race, year, population) values ('Oregon', 'Native Hawaiian or Pacific Islander', 2019, 19245);
insert into census_data (state, race, year, population) values ('New Hampshire', 'Asian', 2019, 40300);
insert into census_data (state, race, year, population) values ('North Dakota', 'Other', 2019, 17583);
insert into census_data (state, race, year, population) values ('North Dakota', 'Native Hawaiian or Pacific Islander', 2019, 615);
insert into census_data (state, race, year, population) values ('North Dakota', 'American Indian or Alaska Native', 2019, 42465);
insert into census_data (state, race, year, population) values ('Ohio', 'Black or African American', 2019, 1525570);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'Other', 2019, 272277);
insert into census_data (state, race, year, population) values ('Oklahoma', 'Black or African American', 2019, 307819);
insert into census_data (state, race, year, population) values ('Delaware', 'American Indian or Alaska Native', 2019, 6564);
insert into census_data (state, race, year, population) values ('Wyoming', 'American Indian or Alaska Native', 2019, 15778);
insert into census_data (state, race, year, population) values ('Utah', 'Native Hawaiian or Pacific Islander', 2019, 33979);
insert into census_data (state, race, year, population) values ('Massachusetts', 'White or Caucasian', 2019, 5554165);
insert into census_data (state, race, year, population) values ('Tennessee', 'White or Caucasian', 2019, 5354405);
insert into census_data (state, race, year, population) values ('Florida', 'American Indian or Alaska Native', 2019, 108950);
insert into census_data (state, race, year, population) values ('Rhode Island', 'All races', 2019, 1059361);
insert into census_data (state, race, year, population) values ('Montana', 'American Indian or Alaska Native', 2019, 71096);
insert into census_data (state, race, year, population) values ('Illinois', 'Native Hawaiian or Pacific Islander', 2019, 8385);
insert into census_data (state, race, year, population) values ('Hawaii', 'White or Caucasian', 2019, 361317);
insert into census_data (state, race, year, population) values ('California', 'Native Hawaiian or Pacific Islander', 2019, 199805);
insert into census_data (state, race, year, population) values ('Virginia', 'Black or African American', 2019, 1696911);
insert into census_data (state, race, year, population) values ('Connecticut', 'American Indian or Alaska Native', 2019, 20567);
insert into census_data (state, race, year, population) values ('Iowa', 'Asian', 2019, 84119);
insert into census_data (state, race, year, population) values ('Iowa', 'White or Caucasian', 2019, 2859080);
insert into census_data (state, race, year, population) values ('Delaware', 'Asian', 2019, 39863);
insert into census_data (state, race, year, population) values ('Colorado', 'Native Hawaiian or Pacific Islander', 2019, 11329);
insert into census_data (state, race, year, population) values ('Connecticut', 'Asian', 2019, 176579);
insert into census_data (state, race, year, population) values ('Virginia', 'Native Hawaiian or Pacific Islander', 2019, 10092);
insert into census_data (state, race, year, population) values ('Nebraska', 'Other', 2019, 44695);
insert into census_data (state, race, year, population) values ('New Mexico', 'Black or African American', 2019, 54772);
insert into census_data (state, race, year, population) values ('North Carolina', 'All races', 2019, 10488084);
insert into census_data (state, race, year, population) values ('Mississippi', 'Other', 2019, 39966);
insert into census_data (state, race, year, population) values ('Nevada', 'White or Caucasian', 2019, 2277552);
insert into census_data (state, race, year, population) values ('New York', 'Black or African American', 2019, 3421123);
insert into census_data (state, race, year, population) values ('New Mexico', 'Other', 2019, 54716);
insert into census_data (state, race, year, population) values ('Montana', 'Black or African American', 2019, 6389);
insert into census_data (state, race, year, population) values ('Utah', 'Other', 2019, 84863);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'All races', 2019, 12801989);
insert into census_data (state, race, year, population) values ('Vermont', 'Other', 2019, 12461);
insert into census_data (state, race, year, population) values ('Kansas', 'Asian', 2019, 92862);
insert into census_data (state, race, year, population) values ('Georgia', 'Native Hawaiian or Pacific Islander', 2019, 12411);
insert into census_data (state, race, year, population) values ('Arkansas', 'All races', 2019, 3017804);
insert into census_data (state, race, year, population) values ('Arizona', 'Asian', 2019, 268723);
insert into census_data (state, race, year, population) values ('Michigan', 'Other', 2019, 252965);
insert into census_data (state, race, year, population) values ('Iowa', 'American Indian or Alaska Native', 2019, 17060);
insert into census_data (state, race, year, population) values ('Illinois', 'Other', 2019, 260815);
insert into census_data (state, race, year, population) values ('Maine', 'White or Caucasian', 2019, 1269326);
insert into census_data (state, race, year, population) values ('Mississippi', 'Native Hawaiian or Pacific Islander', 2019, 1806);
insert into census_data (state, race, year, population) values ('Massachusetts', 'Asian', 2019, 497517);
insert into census_data (state, race, year, population) values ('Minnesota', 'Asian', 2019, 292507);
insert into census_data (state, race, year, population) values ('Maine', 'All races', 2019, 1344212);
insert into census_data (state, race, year, population) values ('Montana', 'Asian', 2019, 9833);
insert into census_data (state, race, year, population) values ('Montana', 'All races', 2019, 1068778);
insert into census_data (state, race, year, population) values ('New Jersey', 'All races', 2019, 8882190);
insert into census_data (state, race, year, population) values ('Indiana', 'Black or African American', 2019, 669596);
insert into census_data (state, race, year, population) values ('Oregon', 'Asian', 2019, 204739);
insert into census_data (state, race, year, population) values ('Wyoming', 'White or Caucasian', 2019, 535371);
insert into census_data (state, race, year, population) values ('New Jersey', 'American Indian or Alaska Native', 2019, 55429);
insert into census_data (state, race, year, population) values ('Kansas', 'Native Hawaiian or Pacific Islander', 2019, 3687);
insert into census_data (state, race, year, population) values ('New Hampshire', 'American Indian or Alaska Native', 2019, 4114);
insert into census_data (state, race, year, population) values ('North Carolina', 'American Indian or Alaska Native', 2019, 165597);
insert into census_data (state, race, year, population) values ('New Mexico', 'American Indian or Alaska Native', 2019, 229794);
insert into census_data (state, race, year, population) values ('North Dakota', 'Black or African American', 2019, 25984);
insert into census_data (state, race, year, population) values ('Virginia', 'Other', 2019, 269556);
insert into census_data (state, race, year, population) values ('Colorado', 'Other', 2019, 180670);
insert into census_data (state, race, year, population) values ('Wisconsin', 'American Indian or Alaska Native', 2019, 68628);
insert into census_data (state, race, year, population) values ('South Carolina', 'All races', 2019, 5148714);
insert into census_data (state, race, year, population) values ('Colorado', 'Black or African American', 2019, 264479);
insert into census_data (state, race, year, population) values ('Arizona', 'Other', 2019, 213483);
insert into census_data (state, race, year, population) values ('Montana', 'Other', 2019, 30329);
insert into census_data (state, race, year, population) values ('Washington DC', 'Native Hawaiian or Pacific Islander', 2019, 923);
insert into census_data (state, race, year, population) values ('Alabama', 'Asian', 2019, 73715);
insert into census_data (state, race, year, population) values ('Arkansas', 'Other', 2019, 66592);
insert into census_data (state, race, year, population) values ('Alaska', 'American Indian or Alaska Native', 2019, 113953);
insert into census_data (state, race, year, population) values ('Oklahoma', 'Other', 2019, 247860);
insert into census_data (state, race, year, population) values ('Delaware', 'All races', 2019, 973764);
insert into census_data (state, race, year, population) values ('Colorado', 'All races', 2019, 5758736);
insert into census_data (state, race, year, population) values ('Indiana', 'American Indian or Alaska Native', 2019, 28340);
insert into census_data (state, race, year, population) values ('Hawaii', 'All races', 2019, 1415872);
insert into census_data (state, race, year, population) values ('Idaho', 'American Indian or Alaska Native', 2019, 31120);
insert into census_data (state, race, year, population) values ('Maine', 'Other', 2019, 24553);
insert into census_data (state, race, year, population) values ('Illinois', 'White or Caucasian', 2019, 9726915);
insert into census_data (state, race, year, population) values ('Georgia', 'Asian', 2019, 463966);
insert into census_data (state, race, year, population) values ('Massachusetts', 'American Indian or Alaska Native', 2019, 34310);
insert into census_data (state, race, year, population) values ('Maryland', 'Native Hawaiian or Pacific Islander', 2019, 6705);
insert into census_data (state, race, year, population) values ('Louisiana', 'White or Caucasian', 2019, 2918843);
insert into census_data (state, race, year, population) values ('Delaware', 'Native Hawaiian or Pacific Islander', 2019, 1059);
insert into census_data (state, race, year, population) values ('South Dakota', 'Black or African American', 2019, 20332);
insert into census_data (state, race, year, population) values ('Texas', 'American Indian or Alaska Native', 2019, 294902);
insert into census_data (state, race, year, population) values ('Nevada', 'Native Hawaiian or Pacific Islander', 2019, 24585);
insert into census_data (state, race, year, population) values ('Utah', 'American Indian or Alaska Native', 2019, 49720);
insert into census_data (state, race, year, population) values ('New Hampshire', 'Other', 2019, 24157);
insert into census_data (state, race, year, population) values ('Montana', 'Native Hawaiian or Pacific Islander', 2019, 920);
insert into census_data (state, race, year, population) values ('Missouri', 'Native Hawaiian or Pacific Islander', 2019, 9857);
insert into census_data (state, race, year, population) values ('Nevada', 'American Indian or Alaska Native', 2019, 51946);
insert into census_data (state, race, year, population) values ('Nebraska', 'Native Hawaiian or Pacific Islander', 2019, 2349);
insert into census_data (state, race, year, population) values ('New Mexico', 'Native Hawaiian or Pacific Islander', 2019, 3341);
insert into census_data (state, race, year, population) values ('New York', 'Asian', 2019, 1753199);
insert into census_data (state, race, year, population) values ('New York', 'American Indian or Alaska Native', 2019, 189748);
insert into census_data (state, race, year, population) values ('Oregon', 'American Indian or Alaska Native', 2019, 77115);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'Black or African American', 2019, 1540092);
insert into census_data (state, race, year, population) values ('Connecticut', 'White or Caucasian', 2019, 2841541);
insert into census_data (state, race, year, population) values ('Tennessee', 'Black or African American', 2019, 1164461);
insert into census_data (state, race, year, population) values ('Washington DC', 'White or Caucasian', 2019, 324581);
insert into census_data (state, race, year, population) values ('Washington', 'Black or African American', 2019, 331924);
insert into census_data (state, race, year, population) values ('Texas', 'Native Hawaiian or Pacific Islander', 2019, 43212);
insert into census_data (state, race, year, population) values ('Minnesota', 'Other', 2019, 145945);
insert into census_data (state, race, year, population) values ('Iowa', 'Native Hawaiian or Pacific Islander', 2019, 4804);
insert into census_data (state, race, year, population) values ('Kentucky', 'Native Hawaiian or Pacific Islander', 2019, 4192);
insert into census_data (state, race, year, population) values ('Illinois', 'American Indian or Alaska Native', 2019, 75500);
insert into census_data (state, race, year, population) values ('West Virginia', 'White or Caucasian', 2019, 1675122);
insert into census_data (state, race, year, population) values ('Wisconsin', 'Black or African American', 2019, 390543);
insert into census_data (state, race, year, population) values ('Mississippi', 'Black or African American', 2019, 1124559);
insert into census_data (state, race, year, population) values ('Missouri', 'All races', 2019, 6137428);
insert into census_data (state, race, year, population) values ('Massachusetts', 'Native Hawaiian or Pacific Islander', 2019, 7410);
insert into census_data (state, race, year, population) values ('Idaho', 'Other', 2019, 45579);
insert into census_data (state, race, year, population) values ('Georgia', 'All races', 2019, 10617423);
insert into census_data (state, race, year, population) values ('Utah', 'Asian', 2019, 85727);
insert into census_data (state, race, year, population) values ('South Carolina', 'Asian', 2019, 94111);
insert into census_data (state, race, year, population) values ('South Dakota', 'Native Hawaiian or Pacific Islander', 2019, 787);
insert into census_data (state, race, year, population) values ('Wisconsin', 'Asian', 2019, 175279);
insert into census_data (state, race, year, population) values ('Kansas', 'American Indian or Alaska Native', 2019, 35063);
insert into census_data (state, race, year, population) values ('Alabama', 'White or Caucasian', 2019, 3389396);
insert into census_data (state, race, year, population) values ('Michigan', 'All races', 2019, 9986857);
insert into census_data (state, race, year, population) values ('Michigan', 'Native Hawaiian or Pacific Islander', 2019, 4186);
insert into census_data (state, race, year, population) values ('Minnesota', 'White or Caucasian', 2019, 4723931);
insert into census_data (state, race, year, population) values ('Hawaii', 'Native Hawaiian or Pacific Islander', 2019, 143549);
insert into census_data (state, race, year, population) values ('Massachusetts', 'Other', 2019, 177199);
insert into census_data (state, race, year, population) values ('Mississippi', 'Asian', 2019, 33032);
insert into census_data (state, race, year, population) values ('Nebraska', 'American Indian or Alaska Native', 2019, 29285);
insert into census_data (state, race, year, population) values ('Louisiana', 'Asian', 2019, 84192);
insert into census_data (state, race, year, population) values ('Maryland', 'White or Caucasian', 2019, 3539444);
insert into census_data (state, race, year, population) values ('New Hampshire', 'All races', 2019, 1359711);
insert into census_data (state, race, year, population) values ('Missouri', 'American Indian or Alaska Native', 2019, 35839);
insert into census_data (state, race, year, population) values ('Rhode Island', 'Black or African American', 2019, 90108);
insert into census_data (state, race, year, population) values ('Mississippi', 'White or Caucasian', 2019, 1758081);
insert into census_data (state, race, year, population) values ('Nevada', 'Asian', 2019, 268166);
insert into census_data (state, race, year, population) values ('New Hampshire', 'White or Caucasian', 2019, 1266097);
insert into census_data (state, race, year, population) values ('Ohio', 'All races', 2019, 11689100);
insert into census_data (state, race, year, population) values ('Ohio', 'White or Caucasian', 2019, 9552736);
insert into census_data (state, race, year, population) values ('Wyoming', 'Black or African American', 2019, 7467);
insert into census_data (state, race, year, population) values ('Wyoming', 'Native Hawaiian or Pacific Islander', 2019, 596);
insert into census_data (state, race, year, population) values ('California', 'All races', 2019, 39512223);
insert into census_data (state, race, year, population) values ('Vermont', 'American Indian or Alaska Native', 2019, 2441);
insert into census_data (state, race, year, population) values ('Maryland', 'All races', 2019, 6045680);
insert into census_data (state, race, year, population) values ('Kentucky', 'White or Caucasian', 2019, 3909923);
insert into census_data (state, race, year, population) values ('Louisiana', 'All races', 2019, 4648794);
insert into census_data (state, race, year, population) values ('Illinois', 'Black or African American', 2019, 1852516);
insert into census_data (state, race, year, population) values ('Louisiana', 'Other', 2019, 81576);
insert into census_data (state, race, year, population) values ('Georgia', 'White or Caucasian', 2019, 6391505);
insert into census_data (state, race, year, population) values ('Minnesota', 'Black or African American', 2019, 395556);
insert into census_data (state, race, year, population) values ('Georgia', 'American Indian or Alaska Native', 2019, 56008);
insert into census_data (state, race, year, population) values ('Indiana', 'Asian', 2019, 174750);
insert into census_data (state, race, year, population) values ('Maryland', 'American Indian or Alaska Native', 2019, 36840);
insert into census_data (state, race, year, population) values ('Minnesota', 'Native Hawaiian or Pacific Islander', 2019, 4214);
insert into census_data (state, race, year, population) values ('Maine', 'Black or African American', 2019, 22691);
insert into census_data (state, race, year, population) values ('Michigan', 'American Indian or Alaska Native', 2019, 73865);
insert into census_data (state, race, year, population) values ('Nebraska', 'White or Caucasian', 2019, 1704129);
insert into census_data (state, race, year, population) values ('Nebraska', 'Black or African American', 2019, 100763);
insert into census_data (state, race, year, population) values ('Oregon', 'White or Caucasian', 2019, 3655136);
insert into census_data (state, race, year, population) values ('Oklahoma', 'Asian', 2019, 94253);
insert into census_data (state, race, year, population) values ('Texas', 'All races', 2019, 28995881);
insert into census_data (state, race, year, population) values ('Michigan', 'White or Caucasian', 2019, 7911567);
insert into census_data (state, race, year, population) values ('Nebraska', 'Asian', 2019, 53187);
insert into census_data (state, race, year, population) values ('Missouri', 'Other', 2019, 146653);
insert into census_data (state, race, year, population) values ('New Jersey', 'Black or African American', 2019, 1337457);
insert into census_data (state, race, year, population) values ('Montana', 'White or Caucasian', 2019, 950211);
insert into census_data (state, race, year, population) values ('Rhode Island', 'American Indian or Alaska Native', 2019, 11453);
insert into census_data (state, race, year, population) values ('New York', 'All races', 2019, 19453561);
insert into census_data (state, race, year, population) values ('South Carolina', 'Other', 2019, 101237);
insert into census_data (state, race, year, population) values ('Nebraska', 'All races', 2019, 1934408);
insert into census_data (state, race, year, population) values ('Maryland', 'Other', 2019, 177743);
insert into census_data (state, race, year, population) values ('North Dakota', 'Asian', 2019, 12860);
insert into census_data (state, race, year, population) values ('New York', 'White or Caucasian', 2019, 13546776);
insert into census_data (state, race, year, population) values ('West Virginia', 'Black or African American', 2019, 64610);
insert into census_data (state, race, year, population) values ('Oregon', 'Other', 2019, 167762);
insert into census_data (state, race, year, population) values ('Iowa', 'Other', 2019, 61902);
insert into census_data (state, race, year, population) values ('Ohio', 'Asian', 2019, 291478);
insert into census_data (state, race, year, population) values ('New Mexico', 'All races', 2019, 2096829);
insert into census_data (state, race, year, population) values ('Arizona', 'Black or African American', 2019, 376997);
insert into census_data (state, race, year, population) values ('Virginia', 'All races', 2019, 8535519);
insert into census_data (state, race, year, population) values ('Maine', 'Native Hawaiian or Pacific Islander', 2019, 455);
insert into census_data (state, race, year, population) values ('California', 'American Indian or Alaska Native', 2019, 649862);
insert into census_data (state, race, year, population) values ('North Dakota', 'White or Caucasian', 2019, 662555);
insert into census_data (state, race, year, population) values ('South Dakota', 'Asian', 2019, 13699);
insert into census_data (state, race, year, population) values ('Vermont', 'Native Hawaiian or Pacific Islander', 2019, 247);
insert into census_data (state, race, year, population) values ('Louisiana', 'Black or African American', 2019, 1524733);
insert into census_data (state, race, year, population) values ('Rhode Island', 'Asian', 2019, 39536);
insert into census_data (state, race, year, population) values ('New Mexico', 'Asian', 2019, 37550);
insert into census_data (state, race, year, population) values ('Nevada', 'Other', 2019, 141604);
insert into census_data (state, race, year, population) values ('New Jersey', 'Native Hawaiian or Pacific Islander', 2019, 10240);
insert into census_data (state, race, year, population) values ('New Jersey', 'White or Caucasian', 2019, 6388804);
insert into census_data (state, race, year, population) values ('Ohio', 'Native Hawaiian or Pacific Islander', 2019, 7055);
insert into census_data (state, race, year, population) values ('Connecticut', 'Black or African American', 2019, 434585);
insert into census_data (state, race, year, population) values ('New Jersey', 'Other', 2019, 203450);
insert into census_data (state, race, year, population) values ('Rhode Island', 'Other', 2019, 30621);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'Native Hawaiian or Pacific Islander', 2019, 9994);
insert into census_data (state, race, year, population) values ('Washington', 'Native Hawaiian or Pacific Islander', 2019, 60349);
insert into census_data (state, race, year, population) values ('West Virginia', 'American Indian or Alaska Native', 2019, 4585);
insert into census_data (state, race, year, population) values ('Vermont', 'Black or African American', 2019, 8774);
insert into census_data (state, race, year, population) values ('South Dakota', 'White or Caucasian', 2019, 748070);
insert into census_data (state, race, year, population) values ('Connecticut', 'Native Hawaiian or Pacific Islander', 2019, 3879);
insert into census_data (state, race, year, population) values ('West Virginia', 'Native Hawaiian or Pacific Islander', 2019, 530);
insert into census_data (state, race, year, population) values ('Delaware', 'Other', 2019, 26659);
insert into census_data (state, race, year, population) values ('Washington', 'Other', 2019, 370139);
insert into census_data (state, race, year, population) values ('Florida', 'White or Caucasian', 2019, 16597392);
insert into census_data (state, race, year, population) values ('Kentucky', 'All races', 2019, 4467673);
insert into census_data (state, race, year, population) values ('South Carolina', 'Native Hawaiian or Pacific Islander', 2019, 5065);
insert into census_data (state, race, year, population) values ('Oklahoma', 'American Indian or Alaska Native', 2019, 371104);
insert into census_data (state, race, year, population) values ('Delaware', 'Black or African American', 2019, 225544);
insert into census_data (state, race, year, population) values ('Rhode Island', 'Native Hawaiian or Pacific Islander', 2019, 2125);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'American Indian or Alaska Native', 2019, 50687);
insert into census_data (state, race, year, population) values ('Maryland', 'Asian', 2019, 406303);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'Asian', 2019, 481877);
insert into census_data (state, race, year, population) values ('New Hampshire', 'Native Hawaiian or Pacific Islander', 2019, 672);
insert into census_data (state, race, year, population) values ('Ohio', 'American Indian or Alaska Native', 2019, 34010);
insert into census_data (state, race, year, population) values ('Pennsylvania', 'White or Caucasian', 2019, 10447062);
insert into census_data (state, race, year, population) values ('Oklahoma', 'Native Hawaiian or Pacific Islander', 2019, 8581);
insert into census_data (state, race, year, population) values ('Florida', 'Other', 2019, 478412);
insert into census_data (state, race, year, population) values ('Oregon', 'Black or African American', 2019, 93740);
insert into census_data (state, race, year, population) values ('Virginia', 'White or Caucasian', 2019, 5922648);
insert into census_data (state, race, year, population) values ('Washington DC', 'American Indian or Alaska Native', 2019, 4130);
insert into census_data (state, race, year, population) values ('Florida', 'Black or African American', 2019, 3633515);
insert into census_data (state, race, year, population) values ('Arizona', 'Native Hawaiian or Pacific Islander', 2019, 20169);
insert into census_data (state, race, year, population) values ('California', 'Other', 2019, 1574115);
insert into census_data (state, race, year, population) values ('Kansas', 'Black or African American', 2019, 178725);
insert into census_data (state, race, year, population) values ('Utah', 'White or Caucasian', 2019, 2904132);
insert into census_data (state, race, year, population) values ('Maine', 'Asian', 2019, 17420);
insert into census_data (state, race, year, population) values ('Minnesota', 'American Indian or Alaska Native', 2019, 77479);
insert into census_data (state, race, year, population) values ('Missouri', 'Asian', 2019, 133312);
insert into census_data (state, race, year, population) values ('New Jersey', 'Asian', 2019, 886810);
insert into census_data (state, race, year, population) values ('North Carolina', 'Other', 2019, 245008);
insert into census_data (state, race, year, population) values ('Ohio', 'Other', 2019, 278251);
insert into census_data (state, race, year, population) values ('North Carolina', 'White or Caucasian', 2019, 7399487);
insert into census_data (state, race, year, population) values ('North Carolina', 'Asian', 2019, 334299);
insert into census_data (state, race, year, population) values ('Missouri', 'Black or African American', 2019, 725579);
insert into census_data (state, race, year, population) values ('North Carolina', 'Native Hawaiian or Pacific Islander', 2019, 13130);
insert into census_data (state, race, year, population) values ('Nevada', 'Black or African American', 2019, 316303);
insert into census_data (state, race, year, population) values ('South Carolina', 'American Indian or Alaska Native', 2019, 28236);
insert into census_data (state, race, year, population) values ('South Dakota', 'Other', 2019, 21767);
insert into census_data (state, race, year, population) values ('Utah', 'Black or African American', 2019, 47537);
insert into census_data (state, race, year, population) values ('Colorado', 'Asian', 2019, 202664);
insert into census_data (state, race, year, population) values ('South Dakota', 'American Indian or Alaska Native', 2019, 80004);
insert into census_data (state, race, year, population) values ('Tennessee', 'Native Hawaiian or Pacific Islander', 2019, 6578);
insert into census_data (state, race, year, population) values ('Florida', 'Native Hawaiian or Pacific Islander', 2019, 24641);
insert into census_data (state, race, year, population) values ('Washington', 'All races', 2019, 7614893);
insert into census_data (state, race, year, population) values ('Oklahoma', 'All races', 2019, 3956971);
insert into census_data (state, race, year, population) values ('Massachusetts', 'Black or African American', 2019, 621902);
insert into census_data (state, race, year, population) values ('Louisiana', 'Native Hawaiian or Pacific Islander', 2019, 2854);
insert into census_data (state, race, year, population) values ('Louisiana', 'American Indian or Alaska Native', 2019, 36596);
insert into census_data (state, race, year, population) values ('Texas', 'Black or African American', 2019, 3739221);
insert into census_data (state, race, year, population) values ('Kentucky', 'Other', 2019, 90171);
insert into census_data (state, race, year, population) values ('Maryland', 'Black or African American', 2019, 1878645);
insert into census_data (state, race, year, population) values ('Nevada', 'All races', 2019, 3080156);
insert into census_data (state, race, year, population) values ('Arkansas', 'White or Caucasian', 2019, 2385258);
insert into census_data (state, race, year, population) values ('Michigan', 'Black or African American', 2019, 1407890);
insert into census_data (state, race, year, population) values ('New York', 'Native Hawaiian or Pacific Islander', 2019, 27034);
insert into census_data (state, race, year, population) values ('New Mexico', 'White or Caucasian', 2019, 1716656);
insert into census_data (state, race, year, population) values ('Florida', 'Asian', 2019, 634827);
insert into census_data (state, race, year, population) values ('South Dakota', 'All races', 2019, 884659);
insert into census_data (state, race, year, population) values ('Connecticut', 'Other', 2019, 88136);
insert into census_data (state, race, year, population) values ('Oregon', 'All races', 2019, 4217737);
insert into census_data (state, race, year, population) values ('Texas', 'Asian', 2019, 1510470);
insert into census_data (state, race, year, population) values ('New Hampshire', 'Black or African American', 2019, 24371);
insert into census_data (state, race, year, population) values ('Washington', 'White or Caucasian', 2019, 5977696);
insert into census_data (state, race, year, population) values ('South Carolina', 'Black or African American', 2019, 1388017);
insert into census_data (state, race, year, population) values ('Michigan', 'Asian', 2019, 336384);
insert into census_data (state, race, year, population) values ('Mississippi', 'All races', 2019, 2976149);
insert into census_data (state, race, year, population) values ('Utah', 'All races', 2019, 3205958);
insert into census_data (state, race, year, population) values ('Kentucky', 'Black or African American', 2019, 378479);
insert into census_data (state, race, year, population) values ('Delaware', 'White or Caucasian', 2019, 674075);
insert into census_data (state, race, year, population) values ('Arkansas', 'Black or African American', 2019, 473048);
insert into census_data (state, race, year, population) values ('Texas', 'White or Caucasian', 2019, 22806130);
insert into census_data (state, race, year, population) values ('North Dakota', 'All races', 2019, 762062);
insert into census_data (state, race, year, population) values ('Wyoming', 'All races', 2019, 578759);